name: Terraform Cleanup

on:
  workflow_dispatch:

jobs:
  terraform-cleanup:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Terraform tool
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      # Configure AWS credentials using session token
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # Set the backend environment variables for Terraform
      - name: Configure Backend Environment
        run: |
          echo "TF_S3_BUCKET=terraforms3hasan" >> $GITHUB_ENV
          echo "TF_S3_BUCKET set to: $TF_S3_BUCKET"

      # Initialize Terraform with backend settings
      - name: Initialize Terraform
        run: |
          terraform init \
            -backend-config="bucket=${{ env.TF_S3_BUCKET }}" \
            -backend-config="key=terraform/state/terraform.tfstate" \
            -backend-config="region=us-east-1"

      # Terraform Destroy command to remove all resources
      - name: Execute Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
